select
  id,
  "textitSessionId",
  "textitContactUuid",
  "textitContactName",
  "createdAt",
  "updatedAt",
  data ->> 'name' as name,
  data ->> 'urns' as urns,
  data ->> 'uuid' as uuid,
  data -> 'fields' ->> 'age' as age,
  data -> 'fields' ->> 'rsc' as rsc,
  data -> 'fields' ->> 'arrsc' as arrsc,
  data -> 'fields' ->> 'gender' as gender,
  data -> 'fields' ->> 'fullrsc' as fullrsc,
  data -> 'fields' ->> 'arfullrsc' as arfullrsc,
  data -> 'fields' ->> 'firstname' as firstname,
  data -> 'fields' ->> 'nationality1' as nationality1,
  data -> 'fields' ->> 'western_left' as western_left,
  data -> 'fields' ->> 'ongoing_usrap' as ongoing_usrap,
  data -> 'fields' ->> 'western_right' as western_right,
  data -> 'fields' ->> 'arnationality1' as arnationality1,
  data -> 'fields' ->> 'has_unhcr_file' as has_unhcr_file,
  data -> 'fields' ->> 'marital_status' as marital_status,
  data -> 'fields' ->> 'minor_or_adult' as minor_or_adult,
  data -> 'fields' ->> 'pause_handoffs' as pause_handoffs,
  data -> 'fields' ->> 'current_country' as current_country,
  data -> 'fields' ->> 'arcurrentcountry' as arcurrentcountry,
  data -> 'fields' ->> 'rsc_contact_email' as rsc_contact_email,
  data -> 'fields' ->> 'unique_session_id' as unique_session_id,
  data -> 'fields' ->> 'relative_abroad_name' as relative_abroad_name,
  data -> 'fields' ->> 'prescreening_complete' as prescreening_complete,
  data -> 'fields' ->> 'relative_abroad_name1' as relative_abroad_name1,
  data -> 'fields' ->> 'relative_abroad_name2' as relative_abroad_name2,
  data -> 'fields' ->> 'resettlement_relatives' as resettlement_relatives,
  data -> 'fields' ->> 'rsc_case_status_portal' as rsc_case_status_portal,
  data -> 'fields' ->> 'previous_us_resettlement' as previous_us_resettlement,
  data -> 'fields' ->> 'relative_abroad_location' as relative_abroad_location,
  data -> 'fields' ->> 'us_relative_relationship' as us_relative_relationship,
  data -> 'fields' ->> 'relative_abroad_location1' as relative_abroad_location1,
  data -> 'fields' ->> 'relative_abroad_location2' as relative_abroad_location2,
  data -> 'fields' ->> 'us_relative_relationship1' as us_relative_relationship1,
  data -> 'fields' ->> 'us_relative_relationship2' as us_relative_relationship2,
  data -> 'fields' ->> 'canadian_private_sponsorhip' as canadian_private_sponsorhip,
  data -> 'fields' ->> 'end_feedback_recommend_rating' as end_feedback_recommend_rating,
  data -> 'fields' ->> 'end_feedback_helpfulness_rating' as end_feedback_helpfulness_rating,
  data -> 'fields' ->> 'canadian_sponsorship_info_rating' as canadian_sponsorship_info_rating,
  data -> 'fields' ->> 'end_feedback_recommend_open_ended' as end_feedback_recommend_open_ended,
  data -> 'fields' ->> 'canadian_sponsorship_info_response' as canadian_sponsorship_info_response,
  data -> 'fields' ->> 'end_feedback_follow_up_conversation' as end_feedback_follow_up_conversation,
  data -> 'fields' ->> 'end_feedback_helpfulness_open_ended' as end_feedback_helpfulness_open_ended,
  data -> 'fields' ->> 'end_feedback_other_information_needs' as end_feedback_other_information_needs,
  data -> 'fields' ->> 'German_Reunification_Info_Rating' as German_Reunification_Info_Rating,
  #query added to include this field
  data -> 'fields' ->> 'Nationality2' as Nationality2,
  #query added to include this field
  data -> 'groups' as groups,
  data ->> 'blocked' as blocked,
  data ->> 'stopped' as stopped,
  data ->> 'language' as language,
  data ->> 'created_on' as created_on,
  data ->> 'modified_on' as modified_on
from public. "TextitSessions"