select
  id,
  "textitSessionId",
  "textitContactUuid",
  "textitContactName",
  "createdAt",
  "updatedAt",
  data ->> 'name' as name,
  data -> 'urns' -> 0 as urns,
  data ->> 'uuid' as uuid,
  data -> 'fields' ->> 'rsc' as rsc,
  data -> 'fields' ->> 'arrsc' as arrsc,
  data -> 'fields' ->> 'gender' as gender,
  data -> 'fields' ->> 'fullrsc' as fullrsc,
  data -> 'fields' ->> 'arfullrsc' as arfullrsc,
  data -> 'fields' ->> 'firstname' as firstname,
  data -> 'fields' ->> 'nationality1' as nationality1,
  data -> 'fields' ->> 'nationality2' as nationality2,
  data -> 'fields' ->> 'nationality3' as nationality3,
  data -> 'fields' ->> 'western_left' as western_left,
  data -> 'fields' ->> 'ongoing_usrap' as ongoing_usrap,
  data -> 'fields' ->> 'western_right' as western_right,
  data -> 'fields' ->> 'arnationality1' as arnationality1,
  data -> 'fields' ->> 'has_unhcr_file' as has_unhcr_file,
  data -> 'fields' ->> 'marital_status' as marital_status,
  data -> 'fields' ->> 'minor_or_adult' as minor_or_adult,
  data -> 'fields' ->> 'pause_handoffs' as pause_handoffs,
  data -> 'fields' ->> 'current_country' as current_country,
  data -> 'fields' ->> 'arcurrentcountry' as arcurrentcountry,
  data -> 'fields' ->> 'rsc_contact_email' as rsc_contact_email,
  data -> 'fields' ->> 'unique_session_id' as unique_session_id,
  data -> 'fields' ->> 'relative_abroad_name' as relative_abroad_name,
  data -> 'fields' ->> 'prescreening_complete' as prescreening_complete,
  data -> 'fields' ->> 'relative_abroad_name1' as relative_abroad_name1,
  data -> 'fields' ->> 'relative_abroad_name2' as relative_abroad_name2,
  data -> 'fields' ->> 'resettlement_relatives' as resettlement_relatives,
  data -> 'fields' ->> 'rsc_case_status_portal' as rsc_case_status_portal,
  data -> 'fields' ->> 'previous_us_resettlement' as previous_us_resettlement,
  data -> 'fields' ->> 'relative_abroad_location' as relative_abroad_location,
  data -> 'fields' ->> 'us_relative_relationship' as us_relative_relationship,
  data -> 'fields' ->> 'relative_abroad_location1' as relative_abroad_location1,
  data -> 'fields' ->> 'relative_abroad_location2' as relative_abroad_location1,
  data -> 'fields' ->> 'us_relative_relationship1' as us_relative_relationship1,
  data -> 'fields' ->> 'us_relative_relationship2' as us_relative_relationship1,
  data -> 'fields' ->> 'canadian_private_sponsorhip' as canadian_private_sponsorhip,
  data -> 'fields' ->> 'end_feedback_recommend_rating' as end_feedback_recommend_rating,
  data -> 'fields' ->> 'end_feedback_helpfulness_rating' as end_feedback_helpfulness_rating,
  data -> 'fields' ->> 'canadian_sponsorship_info_rating' as canadian_sponsorship_info_rating,
  data -> 'fields' ->> 'end_feedback_recommend_open_ended' as end_feedback_recommend_open_ended,
  data -> 'fields' ->> 'canadian_sponsorship_info_response' as canadian_sponsorship_info_response,
  data -> 'fields' ->> 'end_feedback_follow_up_conversation' as end_feedback_follow_up_conversation,
  data -> 'fields' ->> 'end_feedback_helpfulness_open_ended' as end_feedback_helpfulness_open_ended,
  data -> 'fields' ->> 'end_feedback_other_information_needs' as end_feedback_other_information_needs,
  data -> 'fields' ->> 'age' as age,
  data -> 'fields' ->> 'relative_abroad_location3' as relative_abroad_location3,
  data -> 'fields' ->> 'child_illness' as child_illness,
  data -> 'fields' ->> 'hired_lawyer' as hired_lawyer,
  data -> 'fields' ->> 'svt' as svt,
  data -> 'fields' ->> 'women_and_girls_at_risk' as women_and_girls_at_risk,
  data -> 'fields' ->> 'lack_of_durable_solutions' as lack_of_durable_solutions,
  data -> 'fields' ->> 'unaccompanied_minor' as unaccompanied_minor,
  data -> 'fields' ->> 'lgtb' as lgtb,
  data -> 'fields' ->> 'lppn_score' as lppn_score,
  data -> 'fields' ->> 'medical_needs_score' as medical_needs_score,
  data -> 'fields' ->> 'relative_abroad_location4' as relative_abroad_location4,
  data -> 'fields' ->> 'relative_abroad_location5' as relative_abroad_location5,
  data -> 'fields' ->> 'usrap_info_response' as usrap_info_response,
  data -> 'fields' ->> 'usrap_info_rating' as usrap_info_rating,
  data -> 'fields' ->> 'i730_info_rating' as i730_info_rating,
  data -> 'fields' ->> 'i730_info_response' as i730_info_response,
  data -> 'fields' ->> 'i130_info_rating' as i130_info_rating,
  data -> 'fields' ->> 'i130_info_response' as i130_info_response,
  data -> 'fields' ->> 'daprelsiv_info_rating' as daprelsiv_info_rating,
  data -> 'fields' ->> 'daprelsiv_response' as daprelsiv_response,
  data -> 'fields' ->> 'p3_info_rating' as p3_info_rating,
  data -> 'fields' ->> 'p3_info_response' as p3_info_response,
  data -> 'fields' ->> 'dapi130_info_rating' as dapi130_info_rating,
  data -> 'fields' ->> 'dapi130_info_response' as dapi130_info_response,
  data -> 'fields' ->> 'dapev_info_rating' as dapev_info_rating,
  data -> 'fields' ->> 'dapev_info_response' as dapev_info_response,
  data -> 'fields' ->> 'german_reunification_info_rating' as german_reunification_info_rating,
  data -> 'fields' ->> 'german_reunification_info_response' as german_reunification_info_response,
  data -> 'fields' ->> 'icorn_info_rating' as icorn_info_rating,
  data -> 'fields' ->> 'icorn_info_response' as icorn_info_response,
  data -> 'fields' ->> 'unhcr_info_rating' as p3_info_rating,
  data -> 'fields' ->> 'unhcr_info_response' as p3_info_response,
  data -> 'fields' ->> 'vulnerability_assessed' as vulnerability_assessed,
  data -> 'fields' ->> 'handoff_timestamp' as handoff_timestamp,
  data -> 'fields' ->> 'referral_complete' as referral_complete,
  data -> 'groups' as groups,
  data ->> 'blocked' as blocked,
  data ->> 'stopped' as stopped,
  data ->> 'language' as language,
  data ->> 'created_on' as created_on,
  data ->> 'modified_on' as modified_on
from public. "TextitSessions";