psql -h marhub-database2.cytzl3ilzpvr.us-east-1.rds.amazonaws.com -d marhub_dev -U marhub_readonly -c 'COPY (
SELECT "textitSessionId" as "Unique Session Id",
"textitContactUuid" as "Contact UUID",
"createdAt" as "Created On",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'handoff_timestamp' "'" ' as "Handoff Timestamp",
"textitContactName" as "Name",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'ar_full_name' "'" ' as "AR Full Name",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'en_full_name' "'" ' as "EN Full Name",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'fam_num' "'" ' as "Spouse Name",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'email_address1' "'" ' as "Email Address 1",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'phone_number' "'" ' as "Phone Number",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'current_country' "'" ' as "Current Country",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'current_country' "'" ' as "Current Country",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'nationality1' "'" ' as "Nationality1",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'nationality2' "'" ' as "Nationality2",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'nationality3' "'" ' as "Nationality3",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'unhcr_number' "'" ' as "UNHCR Number",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'usrap_case_number' "'" ' as "USRAP Case Number",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'unhcr_case_file_family_adultminor_2' "'" ' as "Kimlik Number",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'lgbt' "'" ' as "LGBT",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'vulnerability_assessed' "'" ' as "Vulnerability Assessed",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'canadian_private_sponsorship' "'" ' as "Canadian Private Sponsorship",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'icorn_cpj' "'" ' as "ICORN CPJ",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'siv' "'" ' as "SIV",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'siv_1059' "'" ' as "SIV 1059",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'siv_101a' "'" ' as "SIV 101a",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'siv_follow_to_join' "'" ' as "SIV Follow to Join",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'us_prior_admission' "'" ' as "US Prior Admission",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'usrap_access' "'" ' as "USRAP Access",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'p_3' "'" ' as "P 3",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'i_730_pathway' "'" ' as "I 730",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'i_130_ir' "'" ' as "I 130 IR",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'i_130_f' "'" ' as "I 130 F",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'dap_via_i_130' "'" ' as "DAP via I 130",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'dap_via_ev' "'" ' as "DAP via EV",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'dap_as_relative_of_siv' "'" ' as "DAP as Relative of SIV",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'germany_family_reunification' "'" ' as "Germany Family Reunification",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'rfr_submission' "'" ' as "RFR Submission",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'eo_waiver' "'" ' as "EO Waiver",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'pro_se_guidance_received' "'" ' as "Pro Se Guidance Received",
data -> ' "'" 'fields' "'" ' ->> ' "'" 'unhcr_case_file_family_adultminor_6' "'" ' as "External Services Info Received"
FROM "TextitSessions"
WHERE "createdAt" > ' "'" '2/02/2020' "'" ' 
ORDER BY "createdAt" ASC)
TO STDOUT WITH CSV HEADER ' > data.csv